import { TesseractLanguageOption, LanguagePreset } from '../types';

export const SUPPORTED_LANGUAGES: TesseractLanguageOption[] = [
  {
    code: 'spa',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    category: 'common',
    description: 'Optimizado para tildes, ñ, signos ¿¡ y vocabulario hispanohablante.',
  },
  {
    code: 'eng',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    category: 'common',
    description: 'Standard English vocabulary, alphanumeric and symbols.',
  },
  {
    code: 'fra',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    category: 'european',
    description: 'Reconnaissance des accents é, è, ê, ç et ligatures.',
  },
  {
    code: 'deu',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    category: 'european',
    description: 'Umlaute ä, ö, ü, Eszett ß und zusammengesetzte Wörter.',
  },
  {
    code: 'ita',
    name: 'Italian',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    category: 'european',
    description: 'Riconoscimento caratteri accentati e sintassi italiana.',
  },
  {
    code: 'por',
    name: 'Portuguese',
    nativeName: 'Português',
    flag: '🇵🇹',
    category: 'european',
    description: 'Suporte a til ~, cedilha ç, crase e acentos graves.',
  },
  {
    code: 'nld',
    name: 'Dutch',
    nativeName: 'Nederlands',
    flag: '🇳🇱',
    category: 'european',
    description: 'Nederlandse woordenschat en diakritische tekens.',
  },
  {
    code: 'pol',
    name: 'Polish',
    nativeName: 'Polski',
    flag: '🇵🇱',
    category: 'european',
    description: 'Polskie znaki diakrytyczne ą, ć, ę, ł, ń, ó, ś, ź, ż.',
  },
  {
    code: 'rus',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    category: 'other',
    description: 'Распознавание кириллического алфавита и символов.',
  },
  {
    code: 'ukr',
    name: 'Ukrainian',
    nativeName: 'Українська',
    flag: '🇺🇦',
    category: 'other',
    description: 'Розпізнавання української кирилиці (є, і, ї, ґ).',
  },
  {
    code: 'chi_sim',
    name: 'Chinese (Simplified)',
    nativeName: '简体中文',
    flag: '🇨🇳',
    category: 'asian',
    description: '简体汉字识别与排版结构解析。',
  },
  {
    code: 'jpn',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    category: 'asian',
    description: '漢字、ひらがな、カタカナの複合認識。',
  },
  {
    code: 'ara',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    category: 'other',
    description: 'التعرف على النص العربي المترابط من اليمين إلى اليسار.',
  },
  {
    code: 'hin',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    category: 'asian',
    description: 'देवनागरी लिपि और मात्राओं की पहचान।',
  },
  {
    code: 'tur',
    name: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    category: 'european',
    description: 'Türkçe karakterler (ç, ğ, ı, ö, ş, ü).',
  },
  {
    code: 'ell',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    flag: '🇬🇷',
    category: 'european',
    description: 'Αναγνώριση ελληνικού αλφαβήτου και τονισμού.',
  },
  {
    code: 'lat',
    name: 'Latin',
    nativeName: 'Latina',
    flag: '🏛️',
    category: 'special',
    description: 'Textos clásicos, terminología jurídica, científica y botánica.',
  },
  {
    code: 'yor',
    name: 'Yoruba',
    nativeName: 'Èdè Yorùbá',
    flag: '🇳🇬',
    category: 'african',
    description: 'Yoruba orthography with subdots (ẹ, ọ, ṣ) and tone accents (á, à, ā, è, ò, etc.).',
  },
  {
    code: 'equ',
    name: 'Math / Equations',
    nativeName: 'Matemáticas',
    flag: '📐',
    category: 'special',
    description: 'Reconocimiento de fórmulas matemáticas y símbolos lógicos.',
  },
];

export const MULTI_ENGINE_PRESETS: LanguagePreset[] = [
  {
    id: 'preset_biz_bilingual',
    name: 'Bilingual Business (ES + EN)',
    description: 'Ideal para contratos, facturas y balances comerciales estándar.',
    languages: ['spa', 'eng'],
    badge: '2 ENGINES',
  },
  {
    id: 'preset_yoruba_bilingual',
    name: 'Yorùbá & English (YOR + EN)',
    description: 'Optimized for bilingual Nigerian legal documents, cultural texts and contracts.',
    languages: ['yor', 'eng'],
    badge: '2 ENGINES',
  },
  {
    id: 'preset_pan_african',
    name: 'Pan-African Polyglot (YOR + EN + FR + SPA + LAT)',
    description: 'Multi-regional coverage for African literature, treaties and international documents.',
    languages: ['yor', 'eng', 'fra', 'spa', 'lat'],
    badge: '5 ENGINES',
  },
  {
    id: 'preset_europe_polyglot',
    name: 'Western Europe Polyglot (ES + EN + FR + DE + IT)',
    description: 'Máxima cobertura para directivas de la UE, manuales y acuerdos transfronterizos.',
    languages: ['spa', 'eng', 'fra', 'deu', 'ita'],
    badge: '5 ENGINES',
  },
  {
    id: 'preset_scientific_math',
    name: 'Scientific & Math (ES + EN + EQU + DEU + LAT)',
    description: 'Optimizado para papers con notación matemática, fórmulas y taxonomía.',
    languages: ['spa', 'eng', 'equ', 'deu', 'lat'],
    badge: '5 ENGINES',
  },
  {
    id: 'preset_legal_classical',
    name: 'Legal Master (ES + EN + LAT + FRA + POR)',
    description: 'Especializado en jurisprudencia, términos en latín y cláusulas notariales.',
    languages: ['spa', 'eng', 'lat', 'fra', 'por'],
    badge: '5 ENGINES',
  },
  {
    id: 'preset_global_multiscript',
    name: 'Global Multi-Script (ES + EN + CHI_SIM + JPN + RUS)',
    description: 'Para documentos con transcripciones CJK, alfabeto cirílico e internacional.',
    languages: ['spa', 'eng', 'chi_sim', 'jpn', 'rus'],
    badge: '5 ENGINES',
  },
];

export const DEFAULT_TESSERACT_CONFIG = {
  selectedLanguages: ['spa', 'eng'], // user can select up to 5
  oem: 1, // LSTM Neural Net
  psm: 3, // Fully automatic page segmentation without OSD
  binarize: true,
  contrastBoost: 25,
  grayscale: true,
  denoise: true,
  sharpen: true,
  detectTables: true,
  detectImages: true,
  detectHeadings: true,
  useAiRefinement: false,
  preserveLineBreaks: true,
};

